Repository SequoiaWynncraft/sequoia-mod, pull requests merged in 2025-01, with the labels that each got.

#3 feat: Add Outer Void Item Scaling
  common/src/main/java/dev/lotnest/sequoia/configs/SequoiaConfigModel.java
  common/src/main/java/dev/lotnest/sequoia/mixins/ItemEntityRendererMixin.java
  common/src/main/resources/assets/sequoia/lang/en_us.json
  common/src/main/resources/sequoia.mixins.json
Labels: enhancement

#4 revert: Remove LootPoolTrackerFeature
  common/src/main/java/dev/lotnest/sequoia/command/commands/VersionCommand.java
  common/src/main/java/dev/lotnest/sequoia/configs/SequoiaConfigModel.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/lootpool/LootPoolItem.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/lootpool/LootPoolTrackerFeature.java
  common/src/main/java/dev/lotnest/sequoia/manager/managers/FeatureManager.java
  common/src/main/java/dev/lotnest/sequoia/mixins/ItemEntityRendererMixin.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/GLootPoolWSMessage.java
  common/src/main/resources/assets/sequoia/lang/en_us.json
  fabric/src/main/resources/fabric.mod.json
  neoforge/src/main/resources/META-INF/neoforge.mods.toml
Labels: enhancement

#7 fix: Make player's guild deduction independent on Wynncraft's API
  build.gradle
  common/src/main/java/dev/lotnest/sequoia/command/commands/ConnectCommand.java
  common/src/main/java/dev/lotnest/sequoia/command/commands/DisconnectCommand.java
  common/src/main/java/dev/lotnest/sequoia/command/commands/OuterVoidCommand.java
  common/src/main/java/dev/lotnest/sequoia/command/commands/ReconnectCommand.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/WebSocketFeature.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/guildraidtracker/RaidType.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/messagefilter/MessageFilterPatterns.java
  common/src/main/java/dev/lotnest/sequoia/json/adapters/ItemResponseIconAdapter.java
  common/src/main/java/dev/lotnest/sequoia/mixins/ClientPacketListenerMixin.java
  common/src/main/java/dev/lotnest/sequoia/utils/EncryptionUtils.java
  common/src/main/java/dev/lotnest/sequoia/utils/URLUtils.java
  common/src/main/java/dev/lotnest/sequoia/ws/WSMessageType.java
  common/src/main/java/dev/lotnest/sequoia/ws/handlers/SMessageHandler.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/GLocationServiceWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/GuildRaidWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/SCommandPipeWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/SMessageWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/discordchatbridge/GChatMessageWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/discordchatbridge/SChannelMessageWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/session/GIdentifyWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/session/SSessionResultWSMessage.java
  common/src/main/java/dev/lotnest/sequoia/wynn/WynnUtils.java
  common/src/main/java/dev/lotnest/sequoia/wynn/api/guild/GuildService.java
  common/src/main/resources/sequoia.mixins.json
  gradle.properties
Labels: bug, enhancement

#10 fix: PoseStack crash on some occasions
  build.gradle
  common/src/main/java/dev/lotnest/sequoia/SequoiaMod.java
  common/src/main/java/dev/lotnest/sequoia/command/commands/OnlineMembersCommand.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/WebSocketFeature.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/guildraidtracker/GuildRaid.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/guildraidtracker/GuildRaidTrackerFeature.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/messagefilter/mod/ModMessageFilterPatterns.java
  common/src/main/java/dev/lotnest/sequoia/feature/features/raids/TNARaidFeature.java
  common/src/main/java/dev/lotnest/sequoia/minecraft/MojangService.java
  common/src/main/java/dev/lotnest/sequoia/mixins/ItemEntityRendererMixin.java
  common/src/main/java/dev/lotnest/sequoia/utils/LongUtils.java
  common/src/main/java/dev/lotnest/sequoia/ws/messages/session/GIdentifyWSMessage.java
  common/src/main/resources/assets/sequoia/lang/en_us.json
Labels: bug
